[{id: 1, label: "Carrot", inLineDistance: 2, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water regularly to keep soil moist"},
{id: 2, label: "Lettuce", inLineDistance: 6, rowDistance: 18, timeToPlant: "Spring & Fall", depth: 0.25, harvestTime: "45 days", wateringInfo: "Water consistently to keep soil moist"},
{id: 3, label: "Tomato", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring", depth: 0.5, harvestTime: "80 days", wateringInfo: "Water deeply and infrequently"},
{id: 4, label: "Cucumber", inLineDistance: 12, rowDistance: 36, timeToPlant: "Spring & Summer", depth: 1.0, harvestTime: "60 days", wateringInfo: "Water deeply once a week"},
{id: 5, label: "Radish", inLineDistance: 1, rowDistance: 6, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "30 days", wateringInfo: "Keep soil moist, water regularly"},
{id: 6, label: "Spinach", inLineDistance: 3, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "45 days", wateringInfo: "Water regularly, especially in dry periods"},
{id: 7, label: "Broccoli", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "100 days", wateringInfo: "Water evenly to maintain moisture"},
{id: 8, label: "Beet", inLineDistance: 3, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 1.0, harvestTime: "55 days", wateringInfo: "Keep soil moist for even growth"},
{id: 9, label: "Pepper", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring", depth: 0.5, harvestTime: "75 days", wateringInfo: "Water regularly, avoid water stress"},
{id: 10, label: "Zucchini", inLineDistance: 18, rowDistance: 36, timeToPlant: "Spring & Summer", depth: 1.0, harvestTime: "50 days", wateringInfo: "Water deeply once a week"},
{id: 11, label: "Corn", inLineDistance: 12, rowDistance: 36, timeToPlant: "Spring", depth: 1.5, harvestTime: "90 days", wateringInfo: "Water regularly during dry spells"},
{id: 12, label: "Potato", inLineDistance: 12, rowDistance: 36, timeToPlant: "Spring", depth: 4.0, harvestTime: "100 days", wateringInfo: "Water evenly, avoid water stress"},
{id: 13, label: "Onion", inLineDistance: 3, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 1.0, harvestTime: "120 days", wateringInfo: "Water to keep soil moist, avoid soggy soil"},
{id: 14, label: "Garlic", inLineDistance: 6, rowDistance: 12, timeToPlant: "Fall", depth: 2.0, harvestTime: "210 days", wateringInfo: "Water sparingly as bulbs mature"},
{id: 15, label: "Pumpkin", inLineDistance: 24, rowDistance: 48, timeToPlant: "Spring", depth: 1.0, harvestTime: "120 days", wateringInfo: "Water deeply once a week"},
{id: 16, label: "Cabbage", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "85 days", wateringInfo: "Water regularly to keep soil moist"},
{id: 17, label: "Kale", inLineDistance: 12, rowDistance: 18, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water regularly, avoid dry spells"},
{id: 18, label: "Cauliflower", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "85 days", wateringInfo: "Water evenly to maintain moisture"},
{id: 19, label: "Basil", inLineDistance: 12, rowDistance: 18, timeToPlant: "Spring & Summer", depth: 0.25, harvestTime: "30 days", wateringInfo: "Keep soil consistently moist"},
{id: 20, label: "Thyme", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water when soil feels dry"},
{id: 21, label: "Chives", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water when soil feels dry"},
{id: 22, label: "Parsley", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.25, harvestTime: "70 days", wateringInfo: "Keep soil moist, water regularly"},
{id: 23, label: "Rhubarb", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 3.0, harvestTime: "120 days", wateringInfo: "Water deeply and infrequently"},
{id: 24, label: "Asparagus", inLineDistance: 18, rowDistance: 48, timeToPlant: "Spring", depth: 6.0, harvestTime: "365 days", wateringInfo: "Water regularly for first year"},
{id: 25, label: "Eggplant", inLineDistance: 24, rowDistance: 24, timeToPlant: "Spring", depth: 0.5, harvestTime: "80 days", wateringInfo: "Water deeply once a week"},
{id: 26, label: "Melon", inLineDistance: 36, rowDistance: 48, timeToPlant: "Spring", depth: 1.0, harvestTime: "90 days", wateringInfo: "Water deeply and infrequently"},
{id: 27, label: "Squash", inLineDistance: 24, rowDistance: 36, timeToPlant: "Spring", depth: 1.0, harvestTime: "50 days", wateringInfo: "Water deeply once a week"},
{id: 28, label: "Chili", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water regularly to avoid drought stress"},
{id: 29, label: "Sweet Potato", inLineDistance: 12, rowDistance: 36, timeToPlant: "Spring", depth: 4.0, harvestTime: "90 days", wateringInfo: "Water deeply and infrequently"},
{id: 30, label: "Fennel", inLineDistance: 12, rowDistance: 18, timeToPlant: "Spring", depth: 1.0, harvestTime: "90 days", wateringInfo: "Water regularly for even growth"},
{id: 31, label: "Celery", inLineDistance: 12, rowDistance: 24, timeToPlant: "Spring", depth: 0.25, harvestTime: "120 days", wateringInfo: "Keep soil moist at all times"},
{id: 32, label: "Artichoke", inLineDistance: 36, rowDistance: 48, timeToPlant: "Spring", depth: 1.0, harvestTime: "150 days", wateringInfo: "Water regularly to avoid drought stress"},
{id: 33, label: "Peas", inLineDistance: 2, rowDistance: 18, timeToPlant: "Spring", depth: 1.0, harvestTime: "60 days", wateringInfo: "Water regularly for best results"},
{id: 34, label: "Turnip", inLineDistance: 3, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 1.0, harvestTime: "60 days", wateringInfo: "Keep soil moist for even growth"},
{id: 35, label: "Pumpkin", inLineDistance: 24, rowDistance: 48, timeToPlant: "Spring", depth: 1.0, harvestTime: "120 days", wateringInfo: "Water deeply once a week"},
{id: 36, label: "Nasturtium", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water regularly to keep soil moist"},
{id: 37, label: "Arugula", inLineDistance: 6, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "30 days", wateringInfo: "Keep soil moist for optimal growth"},
{id: 38, label: "Lemon Balm", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 1.0, harvestTime: "90 days", wateringInfo: "Water when soil feels dry"},
{id: 39, label: "Mint", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "90 days", wateringInfo: "Keep soil moist and well-drained"},
{id: 40, label: "Sage", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "75 days", wateringInfo: "Water when soil feels dry"},
{id: 41, label: "Oregano", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.25, harvestTime: "70 days", wateringInfo: "Water when soil feels dry"},
{id: 42, label: "Cilantro", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "50 days", wateringInfo: "Water consistently for best flavor"},
{id: 43, label: "Fennel", inLineDistance: 12, rowDistance: 18, timeToPlant: "Spring", depth: 1.0, harvestTime: "90 days", wateringInfo: "Water regularly for even growth"},
{id: 44, label: "Chard", inLineDistance: 12, rowDistance: 18, timeToPlant: "Spring & Fall", depth: 1.0, harvestTime: "60 days", wateringInfo: "Water regularly to keep soil moist"},
{id: 45, label: "Endive", inLineDistance: 12, rowDistance: 18, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "75 days", wateringInfo: "Water consistently for optimal growth"},
{id: 46, label: "Bok Choy", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "45 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 47, label: "Kohlrabi", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water consistently for best growth"},
{id: 48, label: "Bitter Melon", inLineDistance: 18, rowDistance: 36, timeToPlant: "Spring", depth: 1.0, harvestTime: "90 days", wateringInfo: "Water deeply once a week"},
{id: 49, label: "Chayote", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "150 days", wateringInfo: "Water deeply and regularly"},
{id: 50, label: "Cranberry", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "365 days", wateringInfo: "Keep soil consistently moist"},
{id: 51, label: "Blueberry", inLineDistance: 48, rowDistance: 48, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 52, label: "Raspberry", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 53, label: "Blackberry", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 54, label: "Strawberry", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 1.0, harvestTime: "60 days", wateringInfo: "Water consistently to keep soil moist"},
{id: 55, label: "Cherry", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 56, label: "Apple", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 57, label: "Peach", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 58, label: "Plum", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 59, label: "Apricot", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 60, label: "Citrus", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 61, label: "Grapes", inLineDistance: 6, rowDistance: 8, timeToPlant: "Spring", depth: 1.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 62, label: "Kiwi", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 2.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 63, label: "Gooseberry", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 1.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 64, label: "Black Currant", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 1.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"},
{id: 65, label: "Red Currant", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 1.0, harvestTime: "365 days", wateringInfo: "Water regularly to maintain moisture"}]