export const dataTest = [
    {id: 1, label: "Carrot", inLineDistance: 2, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water regularly to keep soil moist"},
    {id: 2, label: "Lettuce", inLineDistance: 6, rowDistance: 18, timeToPlant: "Spring & Fall", depth: 0.25, harvestTime: "45 days", wateringInfo: "Water consistently to keep soil moist"},
    {id: 3, label: "Tomato", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring", depth: 0.5, harvestTime: "80 days", wateringInfo: "Water deeply and infrequently"},
]

export const plants = [
    {id: 1, label: "Carrot", inLineDistance: 2, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 2, label: "Lettuce", inLineDistance: 6, rowDistance: 18, timeToPlant: "Spring & Fall", depth: 0.25, harvestTime: "45 days", wateringInfo: "Water with 1 to 1.5 inches of water per week."},
    {id: 3, label: "Tomato", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring", depth: 0.5, harvestTime: "80 days", wateringInfo: "Water with 2 inches of water per week."},
    {id: 4, label: "Cucumber", inLineDistance: 12, rowDistance: 36, timeToPlant: "Spring & Summer", depth: 1.0, harvestTime: "60 days", wateringInfo: "Water with 1.5 to 2 inches of water per week."},
    {id: 5, label: "Radish", inLineDistance: 1, rowDistance: 6, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "30 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 6, label: "Spinach", inLineDistance: 3, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "45 days", wateringInfo: "Water with 1 to 1.5 inches of water per week."},
    {id: 7, label: "Broccoli", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "100 days", wateringInfo: "Water with 1.5 to 2 inches of water per week."},
    {id: 8, label: "Beet", inLineDistance: 3, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 1.0, harvestTime: "55 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 9, label: "Pepper", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring", depth: 0.5, harvestTime: "75 days", wateringInfo: "Water with 1.5 to 2 inches of water per week."},
    {id: 10, label: "Zucchini", inLineDistance: 18, rowDistance: 36, timeToPlant: "Spring & Summer", depth: 1.0, harvestTime: "50 days", wateringInfo: "Water with 1.5 to 2 inches of water per week."},
    {id: 11, label: "Corn", inLineDistance: 12, rowDistance: 36, timeToPlant: "Spring", depth: 1.5, harvestTime: "90 days", wateringInfo: "Water with 1 to 1.5 inches of water per week."},
    {id: 12, label: "Potato", inLineDistance: 12, rowDistance: 36, timeToPlant: "Spring", depth: 4.0, harvestTime: "100 days", wateringInfo: "Water with 1.5 to 2 inches of water per week."},
    {id: 13, label: "Onion", inLineDistance: 3, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 1.0, harvestTime: "120 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 14, label: "Garlic", inLineDistance: 6, rowDistance: 12, timeToPlant: "Fall", depth: 2.0, harvestTime: "210 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 15, label: "Pumpkin", inLineDistance: 24, rowDistance: 48, timeToPlant: "Spring", depth: 1.0, harvestTime: "120 days", wateringInfo: "Water with 2 inches of water per week."},
    {id: 16, label: "Cabbage", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "85 days", wateringInfo: "Water with 1.5 inches of water per week."},
    {id: 17, label: "Kale", inLineDistance: 12, rowDistance: 18, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water with 1 to 1.5 inches of water per week."},
    {id: 18, label: "Cauliflower", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "85 days", wateringInfo: "Water with 1.5 inches of water per week."},
    {id: 19, label: "Basil", inLineDistance: 12, rowDistance: 18, timeToPlant: "Spring & Summer", depth: 0.25, harvestTime: "30 days", wateringInfo: "Water with 1 to 1.5 inches of water per week."},
    {id: 20, label: "Thyme", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 21, label: "Chives", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 22, label: "Parsley", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.25, harvestTime: "70 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 23, label: "Rhubarb", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 3.0, harvestTime: "120 days", wateringInfo: "Water with 2 inches of water per week."},
    {id: 24, label: "Asparagus", inLineDistance: 18, rowDistance: 48, timeToPlant: "Spring", depth: 6.0, harvestTime: "365 days", wateringInfo: "Water with 2 inches of water per week."},
    {id: 25, label: "Eggplant", inLineDistance: 24, rowDistance: 24, timeToPlant: "Spring", depth: 0.5, harvestTime: "80 days", wateringInfo: "Water with 1.5 inches of water per week."},
    {id: 26, label: "Melon", inLineDistance: 36, rowDistance: 48, timeToPlant: "Spring", depth: 1.0, harvestTime: "90 days", wateringInfo: "Water with 2 inches of water per week."},
    {id: 27, label: "Squash", inLineDistance: 24, rowDistance: 36, timeToPlant: "Spring", depth: 1.0, harvestTime: "50 days", wateringInfo: "Water with 2 inches of water per week."},
    {id: 28, label: "Chili", inLineDistance: 18, rowDistance: 24, timeToPlant: "Spring", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water with 1 to 1.5 inches of water per week."},
    {id: 29, label: "Sweet Potato", inLineDistance: 12, rowDistance: 36, timeToPlant: "Spring", depth: 4.0, harvestTime: "90 days", wateringInfo: "Water with 2 inches of water per week."},
    {id: 30, label: "Fennel", inLineDistance: 12, rowDistance: 18, timeToPlant: "Spring", depth: 1.0, harvestTime: "90 days", wateringInfo: "Water with 1.5 inches of water per week."},
    {id: 31, label: "Celery", inLineDistance: 12, rowDistance: 24, timeToPlant: "Spring", depth: 0.25, harvestTime: "120 days", wateringInfo: "Water with 1 to 1.5 inches per week."},
    {id: 32, label: "Artichoke", inLineDistance: 36, rowDistance: 36, timeToPlant: "Spring", depth: 1.5, harvestTime: "180 days", wateringInfo: "Water with 1 to 1.5 inches of water per week."},
    {id: 33, label: "Cilantro", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "50 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 34, label: "Endive", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "75 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 35, label: "Mustard Greens", inLineDistance: 6, rowDistance: 18, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "40 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 36, label: "Sweet Corn", inLineDistance: 12, rowDistance: 36, timeToPlant: "Spring", depth: 1.5, harvestTime: "70 days", wateringInfo: "Water with 1 to 1.5 inches of water per week."},
    {id: 37, label: "Sage", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 38, label: "Oregano", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 39, label: "Rosemary", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 40, label: "Lemon Balm", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 41, label: "Lavender", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "90 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 42, label: "Nasturtium", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "60 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 43, label: "Radicchio", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "80 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 44, label: "Sorrel", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "50 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 45, label: "Kohlrabi", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 1.0, harvestTime: "60 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 46, label: "Bok Choy", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "50 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 47, label: "Pak Choi", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "50 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 48, label: "Collard Greens", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "75 days", wateringInfo: "Water with 1 to 1.5 inches of water per week."},
    {id: 49, label: "Dill", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "40 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 50, label: "Cress", inLineDistance: 6, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.25, harvestTime: "14 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 51, label: "Tarragon", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 52, label: "Curry Plant", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 0.5, harvestTime: "70 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 53, label: "Chervil", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.25, harvestTime: "60 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 54, label: "Shallot", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 1.0, harvestTime: "90 days", wateringInfo: "Water with 1 inch of water per week."},
    {id: 55, label: "Fennel Bulb", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring", depth: 1.0, harvestTime: "90 days", wateringInfo: "Water with 1.5 inches of water per week."},
    {id: 56, label: "Chicory", inLineDistance: 12, rowDistance: 12, timeToPlant: "Spring & Fall", depth: 0.5, harvestTime: "80 days", wateringInfo: "Water with 1 inch of water per week."}
];
        